aml-org/als

Jenkinsfile, als-server/js/node-package/webpack.config.js, build.sbt
Now fails successfully 😆 (https://jenkins.build.msap.io/blue/organizations/jenkins/ALS%2Fals/detail/failJS/1/pipeline/73)
=> Fix JS build and report error

documentation/features/custom-messages.md
- Improve document styling.
- Fix names of the custom methods.
- Add links to LSP specification.
- Fix request parameters for the `serialization` method.
- Fix response payload for the `conversion` method.
- Fix types for "version" parameter of the `didFocusChange` command.
- Fix request parameters of the `serialization` method.
- Add possible values to the `conversion` method's request.
=> Revise "Custom messages" section of the documentation

als-node-client/node-package/typescript/als-node-client.d.ts, als-server/js/node-package/typescript/als-server.d.ts, als-server/shared/src/test/resources/diagnostics/project/api.raml.jsonld, als-server/shared/src/test/resources/diagnostics/project/isolated.raml.jsonld, dependencies.properties
- Update typings
- Update goldens
- Update amf-custom-validator-scalajs
=> Fix ALS 5.0.0

als-common/js/src/main/scala/tmp/TmpResourceLoader.scala, als-common/shared/src/main/scala/org/mulesoft/als/common/FileUtils.scala, als-node-client/node-package/package-lock.json, als-node-client/node-package/package.json, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/FilesEnumeration.scala
Needs change from AMF (currently building)
=> ALS-1899: Fix Windows path regression and adopt change from APIMF-3517

als-server/shared/src/main/scala/org/mulesoft/als/server/modules/diagnostic/custom/TraceParser.scala
depends on https://github.com/aml-org/amf-custom-validator-scalajs/pull/17.
Requires 0.3.0 to be published (or adopt snapshot version).
=> W-10547494: fallback to location in validation result if it cannot be obtained from traces

als-actions/shared/src/test/scala/org/mulesoft/als/actions/selection/SelectionRangeFinderTest.scala, als-server/shared/src/test/resources/suggestions/raml/masterRef/testGroup01/masters/testMaster.raml, als-server/shared/src/test/resources/suggestions/raml/masterRef/testGroup01/masters/testMaster2.raml, als-server/shared/src/test/resources/suggestions/raml/masterRef/testGroup01/test01.raml, als-server/shared/src/test/resources/suggestions/raml/masterRef/testGroup01/test02.raml, als-server/shared/src/test/resources/suggestions/raml/masterRef/testGroup01/test03.raml, als-server/shared/src/test/resources/suggestions/raml/masterRef/testGroup01/test04.raml, als-server/shared/src/test/resources/suggestions/raml/masterRef/testGroup02/test01.raml, als-server/shared/src/test/resources/suggestions/raml/masterRef/testGroup02/test02.raml, als-server/shared/src/test/resources/suggestions/raml/masterRef/testGroup02/testMaster.raml, als-server/shared/src/test/resources/suggestions/raml/masterRef/testGroup02/testMaster2.raml
[W-11092132](https://gus.lightning.force.com/a07EE00000wG3lvYAC): Exchange master for main
=> W-11092132: Exchange master for main

Jenkinsfile
[W-11238723](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000yOYGCYA4/view): Jenkins throws exception in Report to Slack step for branch Support
=> W-11238723: Jenkins throws exception in Report to Slack step for branch Support

als-node-client/node-package/typescript/als-node-client.d.ts, als-node-client/src/main/scala/org/mulesoft/als/nodeclient/Main.scala, als-server/js/node-package/typescript/als-server.d.ts, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/ast/ResolvedUnitListener.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/common/reconciler/Reconciler.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/common/reconciler/Runnable.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/diagnostic/ResolutionDiagnosticManager.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/diagnostic/custom/CustomValidationManager.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/serialization/SerializationManager.scala, als-server/shared/src/test/resources/diagnostics/project/api.raml.jsonld, als-server/shared/src/test/resources/diagnostics/project/isolated.raml.jsonld, als-server/shared/src/test/scala/org/mulesoft/als/server/FailedLogs.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/Flaky.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/LanguageServerBaseTest.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/modules/diagnostic/CustomValidationManagerTest.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/modules/diagnostic/ServerDiagnosticTest.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/modules/hover/HoverTest.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/modules/serialization/SerializationTest.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/workspace/WorkspaceManagerTelemetryTest.scala, als-structure/shared/src/test/resources/OAS20/structure/extensions/at-payload/api.yml.json, als-structure/shared/src/test/resources/semantic/async2/simple1.json, als-structure/shared/src/test/resources/semantic/oas2/simple1.json, als-structure/shared/src/test/resources/semantic/oas3/simple1.json, als-structure/shared/src/test/resources/semantic/raml/simple1.json, dependencies.properties
depends on RC for Custom Validator Scala
=> W-11224427: custom validator JS fixes

Jenkinsfile
Added new condition to do not notify when previous build is Success.
=> fix-slack-notification: Add new condition in Jenkinsfile.

als-server/shared/src/test/scala/org/mulesoft/als/server/modules/serialization/SerializationTest.scala
[W-11224225](https://gus.lightning.force.com/lightning/r/ADM_Sprint__c/a0lEE000000D9QTYA0/view): 
Fix Serialization Test for JsonSchema and a new one for parse and re-serialization was added.
=> W-11224225: Fix Serialization Test for JsonSchema and a new one for parse and re-serialization was added.

als-common/shared/src/main/scala/org/mulesoft/amfintegration/AmfImplicits.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/AMLPathCompletionPlugin.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/pathnavigation/DeclarablePathSuggestor.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/pathnavigation/PathSuggestor.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/webapi/raml/AMLLibraryPathCompletion.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/webapi/raml/WebApiExtensionsPropertyCompletionPlugin.scala, als-suggestions/shared/src/test/scala/org/mulesoft/als/suggestions/PathTest.scala, als-suggestions/shared/src/test/scala/org/mulesoft/als/suggestions/test/oas30/Oas30ComponentRefSuggestionTest.scala
[W-11741265](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000016JDsMYAW/view): Add targetClass to ComponentSuggestor to filter non Schemas in suggestion
=> W-11741265: Filter OAS 3 Component references for specific declared elements

als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/webapi/WebApiTypeFacetsCompletionPlugin.scala, als-suggestions/shared/src/test/resources/test/raml10/by-directory/annotations/declaration-with-prefix-d.raml, als-suggestions/shared/src/test/resources/test/raml10/by-directory/annotations/declaration-with-prefix-m.raml, als-suggestions/shared/src/test/resources/test/raml10/by-directory/annotations/expected/declaration-with-prefix-d.raml.json, als-suggestions/shared/src/test/resources/test/raml10/by-directory/annotations/expected/declaration-with-prefix-m.raml.json, als-suggestions/shared/src/test/resources/test/raml10/by-directory/types/expected/type-properties-with-prefix-m.raml.json, als-suggestions/shared/src/test/resources/test/raml10/by-directory/types/expected/type-properties-with-prefix-p.raml.json, als-suggestions/shared/src/test/resources/test/raml10/by-directory/types/expected/type-properties.raml.json, als-suggestions/shared/src/test/resources/test/raml10/by-directory/types/type-properties-with-prefix-m.raml, als-suggestions/shared/src/test/resources/test/raml10/by-directory/types/type-properties-with-prefix-p.raml, als-suggestions/shared/src/test/resources/test/raml10/by-directory/types/type-properties.raml
Fix wrong suggestions when writing an Annotation Type (RAML) validating the NodeShape is unResolved
=> W-10709800: Fix wrong suggestions when writing an Annotation Type (RAML)

readme.md
=> W-11985087: Update readme.md about json schema

als-actions/shared/src/main/scala/org/mulesoft/als/actions/formatting/RangeFormatting.scala, als-actions/shared/src/test/resources/actions/documentFormatting/yaml/expected/new-lines.raml, als-actions/shared/src/test/resources/actions/documentFormatting/yaml/new-lines.raml, als-actions/shared/src/test/scala/org/mulesoft/als/actions/rangeFormatting/RangeFormattingTest.scala, als-lsp/shared/src/main/scala/org/mulesoft/lsp/configuration/FormattingOptions.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/actions/DocumentRangeFormattingManager.scala
[W-12068188](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001D4jZhYAJ/view): Add mask for range to not trim new lines
=> W-12068188: Do not remove break lines when range formatting

als-actions/shared/src/test/resources/actions/documentFormatting/yaml/expected/new-lines-extended-range.raml, als-actions/shared/src/test/resources/actions/documentFormatting/yaml/new-lines-extended-range.raml, als-common/shared/src/main/scala/org/mulesoft/als/common/YPartBranch.scala
[W-12262497](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001I1L8JYAV/view): Fix range selection
=> W-12262497: Fix range selection

package-lock.json, package.json
W-11867640: Add temporary package.json and clean unused dependencies from package-lock.json
=> W-11867640: Add temporary package.json and clean unused dependencies from package-lock.json

als-structure/shared/src/test/resources/json-schema/draft-03/basic-schema-outline.json, als-structure/shared/src/test/resources/json-schema/draft-04/basic-schema-outline.json, als-structure/shared/src/test/resources/json-schema/draft-07/basic-schema-outline.json, als-structure/shared/src/test/resources/json-schema/draft-2019-09/basic-schema-outline.json, dependencies.properties
W-12353889: Replace expected result, this has to be analyzed in the next sprint
=> W-12353889: Replace expected result

als-server/js/node-package/package.json, dependencies.properties
=> Release 5.3.3: Update dependencies to develop

als-lsp/js/src/main/scala/org/mulesoft/lsp/configuration/ClientTextDocumentClientCapabilities.scala, als-lsp/js/src/main/scala/org/mulesoft/lsp/convert/LspConvertersClientToShared.scala, als-lsp/js/src/test/scala/org/mulesoft/lsp/conversions/ClientConversionTest.scala, als-lsp/shared/src/main/scala/org/mulesoft/lsp/configuration/TextDocumentClientCapabilities.scala, als-server/js/node-package/package.json, als-server/shared/src/main/scala/org/mulesoft/als/server/LanguageServerInitializer.scala
=> W-12257631: Fix lsp formatting capabilities

als-node-client/node-package/package.json, als-server/js/node-package/package.json, dependencies.properties
=> Bump amf.custom.validator.js to snapshot version with polyfill fix

als-node-client/node-package/package-lock.json, als-node-client/node-package/package.json, als-server/js/node-package/package-lock.json, als-server/js/node-package/package.json, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/CompletionPluginsRegistryAML.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/CompletionProviderAST.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/AMLPathCompletionPlugin.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/FilesEnumeration.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/pathnavigation/DeclarablePathSuggestor.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/pathnavigation/PathNavigation.scala, als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/pathnavigation/PathSuggestor.scala, als-suggestions/shared/src/test/resources/test/oas30/oas-components/root-oas/api-ref-schema.yaml, als-suggestions/shared/src/test/resources/test/oas30/oas-components/root-oas/api-wrong-ref.yaml, als-suggestions/shared/src/test/scala/org/mulesoft/als/suggestions/PathTest.scala, als-suggestions/shared/src/test/scala/org/mulesoft/als/suggestions/test/oas30/Oas30ComponentRefSuggestionTest.scala, als-suggestions/shared/src/test/scala/org/mulesoft/als/suggestions/test/oas30/Oas30JsonSchemaRefSuggestionTest.scala
This reverts commit 10bf0360b3eef3db522ae1c76bca85332c97690f.
=> Revert "W-12412172 adding #/ suggestion"

als-node-client/node-package/package.json, als-server/js/node-package/package.json, dependencies.properties
Update version to last SNAPSHOT
=> W-12655871: rc/v5.3.5 0

als-actions/shared/src/test/resources/actions/hover/raml10-full-result.yaml, als-node-client/node-package/package.json, als-server/js/node-package/package.json, als-server/shared/src/test/resources/diagnostics/project/api.raml.jsonld, als-server/shared/src/test/resources/diagnostics/project/isolated.raml.jsonld, dependencies.properties
=> W-12724962: r/5.3.6

als-actions/shared/src/test/resources/actions/hover/raml10-full-result.yaml, als-server/shared/src/test/resources/diagnostics/project/api.raml.jsonld, als-server/shared/src/test/resources/diagnostics/project/isolated.raml.jsonld, dependencies.properties
=> W-12724962/release 5.3.6

Dockerfile
Update Dockerfile in order to run pipelines with Java 17
=> W 12665045/bump java17

als-node-client/node-package/typescript/als-node-client.d.ts, als-server/js/node-package/package.json, als-server/js/node-package/typescript/als-server.d.ts, als-server/js/src/main/scala/org/mulesoft/als/server/protocol/configuration/ClientAlsInitializeParams.scala, als-server/js/src/main/scala/org/mulesoft/als/server/protocol/configuration/ClientAlsServerCapabilities.scala, als-server/js/src/main/scala/org/mulesoft/als/server/protocol/convert/LspConvertersClientToShared.scala, als-server/jvm/src/main/scala/org/mulesoft/als/server/lsp4j/LspConversions.scala, als-server/jvm/src/main/scala/org/mulesoft/als/server/lsp4j/extension/AlsInitializeParams.java, als-server/jvm/src/main/scala/org/mulesoft/als/server/lsp4j/extension/AlsInitializeParamsTypeAdapter.java, als-server/shared/src/main/scala/org/mulesoft/als/server/LanguageServerImpl.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/ManagersFactory.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/configuration/ConfigurationManager.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/configuration/ConfigurationProvider.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/workspace/DefaultProjectConfigurationProvider.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/workspace/MainFileTreeBuilder.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/workspace/WorkspaceContentManager.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/workspace/WorkspaceParserRepository.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/protocol/configuration/AlsInitializeParams.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/protocol/configuration/AlsServerCapabilities.scala, als-server/shared/src/main/scala/org/mulesoft/als/server/workspace/WorkspaceManager.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/modules/diagnostic/CleanDiagnosticTreeTest.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/modules/diagnostic/ProjectErrorConfigurationProvider.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/workspace/DefaultProjectConfigurationProviderTest.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/workspace/WorkspaceCacheTest.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/workspace/WorkspaceDocumentLinksTest.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/workspace/WorkspaceManagerTest.scala, als-server/shared/src/test/scala/org/mulesoft/als/server/workspace/WorkspaceParserRepositoryTest.scala, readme.md
flag in order to disable calculations of all traces in diagnostics
=> W-13214532 - add disableValidationAllTraces

als-lsp/js/src/main/scala/org/mulesoft/lsp/convert/LspConvertersSharedToClient.scala, als-lsp/js/src/main/scala/org/mulesoft/lsp/feature/rename/ClientPrepareRenameDefaultBehavior.scala, als-lsp/jvm/src/main/scala/org/mulesoft/lsp/Lsp4JConversions.scala, als-lsp/shared/src/main/scala/org/mulesoft/lsp/converter/SEither3.scala, als-lsp/shared/src/main/scala/org/mulesoft/lsp/feature/rename/PrepareRenameRequestType.scala, als-node-client/node-package/package-lock.json, als-server/js/node-package/package-lock.json, als-server/js/node-package/package.json, als-server/jvm/src/main/scala/org/mulesoft/als/server/lsp4j/TextDocumentServiceImpl.scala, als-server/jvm/src/main/scala/org/mulesoft/als/server/lsp4j/extension/AlsInitializeParamsTypeAdapter.java, als-server/shared/src/main/scala/org/mulesoft/als/server/modules/actions/rename/PrepareRenameHandler.scala, build.sbt
- Bump_LSP4J: Update version, add dependency and first refactor for Either3
- Bump_LSP4J: Add new dependency and change case for implementation on new lsp4j version.
=> W-13526988: Bump lsp4j to 0.21.0
